articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='articles_page'),
    path('<int:article_id>', views.detail, name='article'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('new_article/', views.new_article, name='new_article'),
    path('<int:article_id>/add_like/', views.add_like, name='add_like'),
    path('public_article/', views.new_article_public, name='new_article_public'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'
urlpatterns = [
    path('registration/', views.index, name='reg'),
    path('registration/create_user',views.create_user,name='create_user')
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('auth.urls')),
    path('profile/', include('userprofile.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('<int:user_id>/edit', views.visible, name='profile_page'),
    path('<int:user_id>/update_info', views.update_info, name='update_info'),
    path('<int:user_id>/', views.visible_user_page, name='user_page'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

userprofile/models.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.html import mark_safe

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    avatar = models.ImageField(upload_to='user_avatar/%Y/%m/%d/', default='user_avatar/avatar.png', blank=True)
    birth_date = models.DateField(null=True, blank=True)

    MALE = 'M'
    FEMALE = 'W'
    ANOTHER = 'ANOTHER'
    NONE = None

    gender = [
        (MALE, 'мужской'),
        (FEMALE, 'женский'),
        (ANOTHER, 'другой'),
        (NONE, 'не выбран'),
    ]
    gender_choice = models.CharField(max_length=7, choices=gender, blank=True)

    def get_avatar(self):
        if not self.avatar:
            return '/media/user_avatar/avatar.png'
        return self.avatar.url

    def avatar_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % self.get_avatar())

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class ProfileAdmin(admin.ModelAdmin):
    list_display = ('avatar_tag', 'user')  # В качестве поля указываем метод, который вернёт тег картинки в списке пользовательских профилей
    readonly_fields = ['avatar_tag']  # обязательно read only режим
    fields = ('avatar_tag', 'user')  # Указываем поля, которые нужно отобразить в административной форме

userprofile/views.py
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from articles.models import Article


# Create your views here.
def visible(request, user_id):
    """Отобразить профиль редактирования пользователя"""
    user = User.objects.get(id=user_id)
    current_article = Article.objects.filter(article_author=request.user)
    return render(request, 'userprofile/profile_edit.html', {'user': user, 'article_list': current_article, 'current_user': request.user.id})


def visible_user_page(request, user_id):
    """Отобразить профиль пользователя с его информацией для всех пользователей"""
    user = User.objects.get(id=user_id)
    current_article = Article.objects.filter(article_author=user_id)
    liked_article = Article.objects.filter(likes=user.id)

    return render(request, 'userprofile/profile_user_page.html', {'user': user, 'current_article': current_article, 'current_user': request.user.id, 'liked_article': liked_article})


def update_info(request, user_id):
    """Обновить информацию в профиле"""
    user = User.objects.get(id=user_id)
    user.first_name = request.POST['first_name']
    user.last_name = request.POST['last_name']
    user.profile.gender_choice = request.POST['gender']
    user.profile.bio = request.POST['bio']
    user.profile.birth_date = request.POST['date_br']
    try:
        user.profile.avatar = request.FILES['avatar_user']
    except:
        user.profile.avatar = user.profile.avatar
    user.save()
    return HttpResponseRedirect(reverse('userprofile:user_page', args=(user_id,)))

templates/userprofile/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock %}
{% block title %}Редактировать профиль{% endblock %}
{% block content %}
    {% if  user.id == current_user %}


        <div class="container bootstrap snippet">
        <div class="row">
            <div class="col-sm-12"><h1>{{ user.username }}</h1></div>
        </div>
        <div class="row">
            <div class="col-sm-3"><!--left col-->


                <div class="text-center">
                    <br>
                    <img src="{{ user.profile.avatar.url }}" class="avatar img-circle img-thumbnail"
                         alt="avatar" style="height: 202px;width: 202px;">
                    <br>
                    <input type="file" class="text-center center-block file-upload" form="data_form"
                           name="avatar_user">
                </div>

                <br>
                <ul class="list-group">
                    <li class="list-group-item text-muted">Статистика <i class="fa fa-dashboard fa-1x"></i></li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Понравилось публикаций</strong></span> {{ user.likes.count }}
                    </li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Публикаций</strong></span> {{ article_list.count }}
                    </li>

                </ul>


            </div><!--/col-3-->
            <div class="col-sm-9">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home">Общие</a></li>
                </ul>


                <div class="tab-content">
                    <div class="tab-pane active" id="home">
                        <hr>
                        <form class="form" action="{% url 'userprofile:update_info' current_user %}" method="post"
                              id="data_form"
                              enctype="multipart/form-data" name="form_main">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label for="first_name"><h4>Имя</h4></label>
                                    <input type="text" class="form-control" name="first_name" id="first_name"
                                           placeholder="Имя" value="{{ user.first_name }}">
                                </div>
                            </div>
                            <div class="form-group">

                                <div class="col-xs-6">
                                    <label for="last_name"><h4>Фамилия</h4></label>
                                    <input type="text" class="form-control" name="last_name" id="last_name"
                                           placeholder="Фамилия" value="{{ user.last_name }}">
                                </div>
                            </div>

                            <div class="form-group">

                                <div class="col-xs-6">
                                    <label for="birth"><h4>Дата рождения</h4></label>
                                    <input type="date" class="form-control" id="birth" name="date_br" required
                                           value="{{ user.profile.birth_date.isoformat }}">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label for="gender"><h4>Пол</h4></label>
                                    <select class="form-control" style="min-height: 34px; min-width: 225px;"
                                            id="gender" name="gender">
                                        <option>Мужской</option>
                                        <option>Женский</option>
                                        <option>Другой</option>
                                        <option selected>Не выбрано</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">

                                <div class="col-xs-6">
                                    <label for="bio"><h4>О себе</h4></label>
                                    <textarea id="bio" name="bio" class="form-control">{{ user.profile.bio }}</textarea>
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-xs-12">
                                    <br>
                                    <button class="btn btn-lg btn-success" type="submit"><i
                                            class="glyphicon glyphicon-ok-sign"></i> Сохранить
                                    </button>
                                    <button class="btn btn-lg" type="reset"><i
                                            class="glyphicon glyphicon-repeat"></i>
                                        Сбросить
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div><!--/tab-pane-->


                </div><!--/tab-content-->

            </div><!--/col-9-->
        </div><!--/row-->
        <script>
            $(document).ready(function () {


                var readURL = function (input) {
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $('.avatar').attr('src', e.target.result);
                        }

                        reader.readAsDataURL(input.files[0]);
                    }
                }


                $(".file-upload").on('change', function () {
                    readURL(this);
                });
            });
        </script>
    {% else %}
        <h1>Это не ваш аккаунт!!!!</h1>
    {% endif %}
{% endblock %}

templates/userprofile/profile_user_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

{% endblock %}
{% block title %}Редактировать профиль{% endblock %}
{% block content %}
    <div class="container bootstrap snippet">
        <div class="row">
            <div class="col-sm-10"><h1>{{ user.username }}</h1></div>

        </div>
        <div class="row">
            <div class="col-sm-3"><!--left col-->


                <div class="text-center">
                    {% if user.profile.avatar == '' %}
                        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png"
                             class="avatar img-circle img-thumbnail"
                             alt="avatar">
                    {% else %}
                        <img src="{{ user.profile.avatar.url }}" class="avatar img-circle img-thumbnail"
                             alt="avatar" style="height: 202px;width: 202px;">
                    {% endif %}
                </div>

                <br>

                <ul class="list-group">
                    <li class="list-group-item text-muted">Статистика<i class="fa fa-dashboard fa-1x"></i></li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Понравилось публикаций</strong></span>{{ user.likes.count }}
                    </li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Публикаций</strong></span> {{ current_article.count }}
                    </li>
                </ul>
                <br>
                {% if user.id == current_user %}
                    <form action="{% url 'userprofile:profile_page' current_user %}" method="post">
                        {% csrf_token %}
                        <button class="btn badge-info">Редактировать
                        </button>
                    </form>
                {% endif %}


            </div><!--/col-3-->
            <div class="col-sm-9">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#home">Общие</a></li>
                    <li><a data-toggle="tab" href="#settings">Публикации</a></li>
                    <li><a data-toggle="tab" href="#messages">Понравившееся публикации</a></li>
                </ul>


                <div class="tab-content">
                    <div class="tab-pane active" id="home">

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="first_name"><h4>Имя</h4></label>
                                <input type="text" class="form-control" name="first_name" id="first_name"
                                       placeholder="Имя" value="{{ user.first_name }}" readonly>
                            </div>
                        </div>
                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="last_name"><h4>Фамилия</h4></label>
                                <input type="text" class="form-control" name="last_name" id="last_name"
                                       placeholder="Фамилия" value="{{ user.last_name }}" readonly>
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="birth"><h4>Дата рождения</h4></label>
                                <input type="date" class="form-control" id="birth" name="date_br" required
                                       value="{{ user.profile.birth_date.isoformat }}" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="gender"><h4>Пол</h4></label>
                                <input type="text" class="form-control" name="last_name" id="gender"
                                       placeholder="Пол" value="{{ user.profile.gender_choice }}" readonly
                                       style="min-height: 34px; min-width: 225px;">
                            </div>
                        </div>
                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="bio"><h4>О себе</h4></label>
                                <textarea id="bio" name="bio" readonly
                                          class="form-control">{{ user.profile.bio }}</textarea>
                            </div>
                        </div>


                        <hr>

                    </div><!--/tab-pane-->
                    <div class="tab-pane" id="messages">

                        <div class="album py-5 bg-light">
                            <br>
                            <div class="row">
                                {% for article in liked_article %}
                                    <div class="col-md-4">
                                        <div class="card mb-4 shadow-sm">

                                            <img class="bd-placeholder-img card-img-top" focusable="false"
                                                 role="img"
                                                 width="100%" height="100%" src="{{ article.article_poster.url }}">


                                            <div class="card-body">

                                                <p class="card-text">{{ article.article_title }}
                                                    {% if article.was_published_recently %}
                                                        <span class="badge badge-secondary">Новая статья!</span></p>
                                                    {% endif %}
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <div class="btn-group">
                                                        <form action="{% url 'articles:article' article.id %}">
                                                            <button type="submit"
                                                                    class="btn btn-sm btn-outline-secondary">
                                                                Посмотреть
                                                            </button>
                                                        </form>
                                                    </div>
                                                    <small class="text-muted">{{ article.article_date }}</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                </div>
                    <div class="tab-pane" id="settings">


                        <div class="album py-5 bg-light">
                            <br>
                            <div class="row">
                                {% for article in current_article %}
                                    <div class="col-md-4">
                                        <div class="card mb-4 shadow-sm">

                                            <img class="bd-placeholder-img card-img-top" focusable="false"
                                                 role="img"
                                                 width="100%" height="100%" src="{{ article.article_poster.url }}">


                                            <div class="card-body">

                                                <p class="card-text">{{ article.article_title }}
                                                    {% if article.was_published_recently %}
                                                        <span class="badge badge-secondary">Новая статья!</span></p>
                                                    {% endif %}
                                                <div class="d-flex justify-content-between align-items-center">
                                                    <div class="btn-group">
                                                        <form action="{% url 'articles:article' article.id %}">
                                                            <button type="submit"
                                                                    class="btn btn-sm btn-outline-secondary">
                                                                Посмотреть
                                                            </button>
                                                        </form>
                                                    </div>
                                                    <small class="text-muted">{{ article.article_date }}</small>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div><!--/tab-pane-->
            </div><!--/tab-content-->

        </div><!--/col-9-->
    </div><!--/row-->
{% endblock %}