articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='articles_page'),
    path('<int:article_id>', views.detail, name='article'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('new_article/', views.new_article, name='new_article'),
    path('<int:article_id>/add_like/', views.add_like, name='add_like'),
    path('public_article/', views.new_article_public, name='new_article_public'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'
urlpatterns = [
    path('registration/', views.index, name='reg'),
    path('registration/create_user',views.create_user,name='create_user')
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('auth.urls')),
    path('profile/', include('userprofile.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('<int:user_id>/edit', views.visible, name='profile_page'),
    path('<int:user_id>/update_info', views.update_info, name='update_info'),
    path('<int:user_id>/', views.visible_user_page, name='user_page'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

articles/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.

class Article(models.Model):
    objects = models.Manager()
    article_author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор статьи')
    article_title = models.CharField('заголовок статьи', max_length=255)
    article_text = models.TextField('текст статьи')
    article_date = models.DateTimeField('дата публикации статьи', auto_now_add=True)
    article_poster = models.ImageField(upload_to='poster_image/%Y/%m/%d/')
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.article_date >= (timezone.now() - datetime.timedelta(days=1))

    def total_likes(self):
        return self.likes.count()


class ArticleStatistic(models.Model):
    class Meta:
        db_table = 'ArticleStatistic'

    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    date = models.DateField('дата', default=timezone.now)
    views = models.IntegerField('просмотры', default=0)

    def __str__(self):
        return self.article.article_title


class ArticleStatisticAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'date', 'views')
    search_fields = ('__str__',)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор комментария')
    comment_text = models.CharField('текст комментария', max_length=255)

    def __str__(self):
        return self.comment_text

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

articles/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget

from .models import Comment, Article


class CommentForm(forms.ModelForm):
    foo = forms.CharField(widget=SummernoteWidget(attrs={
        'summernote':
            {'width': '100%', 'height': '400px',
             'placeholder': 'Комментарий',
             'lazy': True,
             'lang': 'ru-Ru',
             'disableDragAndDrop': True,
             'disable_attachment': True,
             'fontNames': ['Verdana'],
             'disableGrammar': False,
             'fontNamesIgnoreCheck': ['Arial', 'Segoe UI', 'Arial', 'Comic Sans MS', 'Courier New', 'Segoe UI Emoji', 'Segoe UI Symbol'],
             'toolbar': [
                 ['stye', ['style']],
                 ['font', ['bold', 'underline', 'clear']],
                 ['fontname', ['fontname']],
                 ['color', ['color']],
                 ['para', ['ul', 'ol', 'paragraph']],
                 ['table', ['table']],
                 ['insert', ['link']],
                 ['view', ['fullscreen', 'codeview']]], }
    }
    ))

    class Meta:
        model = Comment
        fields = ['comment_text']


class ArticleForm(forms.ModelForm):
    bar = forms.CharField(widget=SummernoteWidget(attrs={
        'summernote':
            {'width': '100%', 'height': '400px',
                'placeholder': 'Статья',
                'lang': 'ru-Ru'

            }

    }
    ))

    class Meta:
        model = Article
        fields = ['article_text']

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

articles/views.py
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .forms import CommentForm, ArticleForm
from .models import Article


# Create your views here.

def index(request):
    article = Article.objects.order_by('-article_date')
    return render(request, 'articles/list.html', {'article': article})


def detail(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except:
        return Http404('Статья не найдена')
    latest_comments_list = article.comment_set.order_by('-id')
    form = CommentForm()
    is_liked = False
    if article.likes.filter(id=request.user.id).exists():
        is_liked = True
    return render(request, 'articles/detail.html', {'article': article, 'latest_comments_list': latest_comments_list, 'form': form, 'is_liked': is_liked, 'total_likes': article.total_likes()})


def new_article(request):
    article_form = ArticleForm()
    return render(request, 'articles/new_article.html', {'form_article': article_form})


def add_like(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except:
        return Http404('Статья не найдена')
    is_liked = False
    if article.likes.filter(id=request.user.id).exists():
        article.likes.remove(request.user)
        is_liked = False
    else:
        article.likes.add(request.user)
        is_liked = True
    return HttpResponseRedirect(reverse('articles:article', args=(article.id,)))


def leave_comment(request, article_id):
    try:
        user = User.objects.get(username=request.user.get_username())
        article = Article.objects.get(id=article_id)
    except:
        return Http404('Статья не найдена')
    article.comment_set.create(comment_author=user, comment_text=request.POST['foo'])
    return HttpResponseRedirect(reverse('articles:article', args=(article.id,)))


def new_article_public(request):
    """Публикация новой статьи"""
    user = User.objects.get(pk=request.user.id)
    title = request.POST['title_article']
    text = request.POST['bar']
    poster = request.FILES['article_poster']
    Article.objects.create(article_author=user, article_title=title, article_text=text, article_poster=poster)
    return HttpResponseRedirect(reverse('articles:articles_page'))

templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Статья: {{ article.article_title|safe }}{% endblock %}

{% block content %}
    <main role="main" class="flex-shrink-0">

        <!-- Begin page content -->

        <div class="container" style="background-color: #F1EEE8">
            <h1 class="mt-5">{{ article.article_title|safe }}



                {% if article.was_published_recently %}
                    <span class="badge badge-secondary">
                    Новая статья!
                    </span>

                {% endif %}


            </h1>
            <div class="row">
                <div class="col">
                    <p class="lead">

                        <strong>

                            Автор: <a style="color: #212529"
                                      href="{% url 'userprofile:user_page' article.article_author.id %}"> {{ article.article_author }}</a>

                        </strong>

                        Дата публикации: {{ article.article_date }}

                        <script src="https://yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>

                        <script src="https://yastatic.net/share2/share.js"></script>

                    <div class="ya-share2"
                         data-services="vkontakte,facebook,odnoklassniki,twitter,viber,whatsapp,telegram">

                    </div>
                </div>

            </div>


            <p>{{ article.article_text|safe }}</p>
            <br>
            {% if request.user.is_authenticated %}
                <form action="{% url 'articles:add_like' article.id %}" method="post">
                    {% csrf_token %}

                    {% if is_liked %}
                        <a href="{% url 'articles:add_like'  article.id %}"><img
                                style="min-width: 40px;min-height: 40px;"
                                src="{% static 'articles/images/like_push.svg' %}"
                                alt="dislike"> </a>
                    {% else %}
                        <a href="{% url 'articles:add_like' article.id %}"> <img
                                style="min-width: 40px;min-height: 40px;"
                                src="{% static 'articles/images/like_svg.svg' %}"
                                alt="like"></a>


                    {% endif %}
                    <br>
                    <strong>Like: {{ total_likes|safe }}</strong>
                </form>
                <br>
            {% else %}
                <div class="jumbotron">
                    <h1 class="display-4">Авторизуйтесь, чтобы поставить оценку</h1>
                    <p class="lead"></p>
                    <hr class="my-4">

                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{ request.path }}"
                           role="button">Войти</a>
                        <a class="btn btn-primary btn-lg" href="{% url 'auth:reg' %}?next={{ request.path }}"
                           role="button">Зарегистрироваться</a>
                    </p>
                </div>
                <br>
            {% endif %}
        </div>

    </main>

    <footer class="footer mt-auto py-3">
        <div class="container" style="background-color:#F1EEE8;">

            {% if latest_comments_list %}
                {% for c in latest_comments_list %}
                    <h5 class="text">Комментарии</h5>
                    <p>

                        <strong>
                            <a href="{% url 'userprofile:user_page' c.comment_author.id %}"
                               style="color: #212529"> {{ c.comment_author }}</a>
                        </strong>

                        <br>

                        {{ c.comment_text|safe }}

                    </p>


                {% endfor %}

            {% else %}
                <h5>Комментариев нет, оставьте его первым!</h5>
            {% endif %}

            {# Форма для комментария #}

            {% if user.is_authenticated %}
                <h6>Оставить комментарий</h6>
                <form action="{% url 'articles:leave_comment'  article.id %}" method="post" class="form-signin">

                    {% csrf_token %}

                    <div class="container">
                        {{ form.foo }}
                    </div>
                    <br>
                    <div class="button-container">
                        <button type="submit" class="btn btn-info allicon">
                            Оставить комментарий
                        </button>
                    </div>

                </form>

            {% else %}
                <div class="jumbotron">
                    <h1 class="display-4">Авторизуйтесь, чтобы принять участие в обсуждении.</h1>
                    <p class="lead"></p>
                    <hr class="my-4">

                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{ request.path }}"
                           role="button">Войти</a>
                        <a class="btn btn-primary btn-lg" href="{% url 'auth:reg' %}?next={{ request.path }}"
                           role="button">Зарегистрироваться</a>
                    </p>
                </div>


            {% endif %}
            <br>
        </div>

    </footer>
{% endblock %}

templates/articles/list.html
{% extends 'base.html' %}
{% load  static %}

{% block title %}Статьи{% endblock %}

{% block content %}
    {% if article %}
        <div class="album py-5 bg-light">
            <div class="container" style="background-color: #f1eee8">
                <br>
                <div class="row">
                    {% for article in article %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">

                                <img class="bd-placeholder-img card-img-top" focusable="false" role="img"
                                     width="100%" height="100%" src="{{ article.article_poster.url }}">


                                <div class="card-body">

                                    <p class="card-text">{{ article.article_title }}
                                        {% if article.was_published_recently %}
                                            <span class="badge badge-secondary">Новая статья!</span></p>
                                        {% endif %}
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <form action="{% url 'articles:article' article.id %}">
                                                <button type="submit" class="btn btn-sm btn-outline-secondary">
                                                    Посмотреть
                                                </button>
                                            </form>
                                        </div>
                                        <small class="text-muted">{{ article.article_date }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <br>
    {% else %}
        <h1>Статей нет...</h1>
    {% endif %}
{% endblock %}

templates/articles/new_article.html
{% extends 'base.html' %}


{% block title %}Написать статью{% endblock %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="container">
        <div class="form-group align-items-center">
            <form action="{% url 'articles:new_article_public' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <br>
                <label for="exampleFormControlFile1">Добавьте заголовок</label>
                <input name="title_article" maxlength="180" class="form-control">
                <br>
                {{ form_article.bar }}

                <label for="exampleFormControlFile1">Добавьте постер</label>
                <input type="file" class="form-control-file" name="article_poster"
                       accept="image/*">
                <br>
                <button type="submit" class="btn btn-primary" value="Сохранить" name="save">Опубликовать</button>
            </form>

        </div>
    {% else %}
        <div class="jumbotron">
            <h1 class="display-4">Авторизуйтесь, чтобы написать статью</h1>
            <p class="lead"></p>
            <hr class="my-4">

            <p class="lead">
                <a class="btn btn-primary btn-lg" href="{% url 'login' %}?next={{ request.path }}"
                   role="button">Войти под своим логином</a>
                <a class="btn btn-primary btn-lg" href="{% url 'auth:reg' %}?next={{ request.path }}"
                   role="button">Зарегистрироваться</a>
                <a class="btn btn-primary btn-lg" href="#" role="button">Зарегистрироваться</a>
            </p>
        </div>
    {% endif %}
</div>

{% endblock %}