articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='articles_page'),
    path('<int:article_id>', views.detail, name='article'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('new_article/', views.new_article, name='new_article'),
    path('<int:article_id>/add_like/', views.add_like, name='add_like'),
    path('public_article/', views.new_article_public, name='new_article_public'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

auth/urls.py
from django.urls import path

from . import views

app_name = 'auth'
urlpatterns = [
    path('registration/', views.index, name='reg'),
    path('registration/create_user',views.create_user,name='create_user')
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('auth.urls')),
    path('profile/', include('userprofile.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'
urlpatterns = [
    path('<int:user_id>/edit', views.visible, name='profile_page'),
    path('<int:user_id>/update_info', views.update_info, name='update_info'),
    path('<int:user_id>/', views.visible_user_page, name='user_page'),
]

#  Copyright (c) 2020.  Designed TheFox https://github.com/TheFox267

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% block head %}
    <head>
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
              integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
              crossorigin="anonymous">

        <!-- JS, Popper.js, and jQuery -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
                integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
                integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
                crossorigin="anonymous"></script>

        <meta charset="UTF-8">
        <title>{% block title %}Мой сайт{% endblock %}</title>
    </head>
{% endblock %}
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'articles:articles_page' %}">
        <img src="{% static 'articles/images/fox_svg.svg' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        FoxSite
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="mr-auto"></div>
        <ul class="navbar-nav my-2 my-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'articles:articles_page' %}">Статьи<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                   data-display="static"
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Профиль
                </a>

                <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
                    {% if user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'userprofile:user_page' request.user.id %}">Перейти в
                            профиль</a>
                        <a class="dropdown-item" href="{% url 'articles:new_article' %}">Написать статью</a>
                        <a class="dropdown-item" href="{% url 'logout' %}">Выход из системы</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'login' %}">Вход</a>
                    {% endif %}
                </div>

            </li>

        </ul>

    </div>
</nav>
{% block content %}

{% endblock %}
</body>
</html>